version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dental-care
      - FRONTEND_URL=http://localhost:5173
      - ML_API_URL=http://ml-service:8000/predict
    depends_on:
      - mongodb
      - ml-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=dental-care

  ml-service:
    build:
      context: ./ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
      - model_data:/app/models

volumes:
  mongodb_data:
  model_data: