services:
  frontend:
    build:
      context: ./frontend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - ml-service

  ml-service:
    build:
      context: ./ml-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service:/app
      - model_data:/app/models

volumes:
  model_data:
  backend_node_modules:
  frontend_node_modules:
